language: node_js
node_js:
  - "6"
services:
  - docker
install: 
  - npm install
  - npm install -g codecov
  - ./test/scripts/install.sh
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
    #- if [ "$TRAVIS_BRANCH" = "master" ]; then docker build . -t nlpm:ubuntu -f test/docker/ubuntu/Dockerfile; fi
    #- if [ "$TRAVIS_BRANCH" = "master" ]; then docker run --user user nlpm:ubuntu /bin/bash -c "source ~/.nvm/nvm.sh; cd /home/user/nlpm; ./app.js install; false; exit $?"; fi
    #- docker run --user user nlpm:ubuntu /bin/bash -c "source ~/.nvm/nvm.sh; cd /home/user/nlpm; ./app.js install; false; exit $?"
    #- if [ "$TRAVIS_BRANCH" = "master" ]; then docker run --user user nlpm:ubuntu /bin/bash -c "source ~/.nvm/nvm.sh; cd /home/user/nlpm; ./app.js install; exit $?"; fi
    #- exit $?
  - ./test/scripts/run.sh
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov -t 50208e3e-79ee-444d-ae99-d0a3ffe48eb5
